spring:
    kafka:
        bootstrap-servers: 10.255.1.115:9092
        producer:
            retries: 0
            batch-size: 16384
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: test-consumer-group
            auto-offset-reset: earliest
            enable-auto-commit: true
            auto-commit-interval: 100
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    data:
        elasticsearch:
            cluster-name: my-application
            cluster-nodes: 10.255.1.115:9300




